name: Deploy to Production
on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Type "deploy" to confirm'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_deploy == 'deploy'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.WORK_FLOW_TOKEN }}

      - name: Rebase prod to master and deploy
        run: |
          git config user.name "NedaaBot"
          git config user.email "186649556+NedaaBot@users.noreply.github.com"
          git switch master
          git pull origin master
          git switch prod
          git rebase master
          git push --force-with-lease origin prod
